w1 = int(input("ENTER THE WIDTH FOR THE FIRST RECTANGLE"))
l1 = int(input("ENTER THE LENGTH FOR THE FIRST RECTANGLE"))
w2 = int(input("ENTER THE WIDTH FOR THE SECOND RECTANGLE"))
l2 = int(input("ENTER THE LENGTH FOR THE SECOND RECTANGLE"))

r1 = w1*l1
r2 = w2*l2

if r1 > r2:
    print("THE FIRST RECTANGLE IS LARGER")
elif r2 > r1:
    print("THE SECOND RECTANGLE IS LARGER")
else:
    print("THE RECTANGLES HAVE THE SAME AREA")

